### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Blair-Johnson** [Finspire13/pytorch-policy-gradient-example#1]
- [ ] Set up / find good tree data structure for doing checks and traversal
- [ ] Create and store dictionary of tokens for each expression
- [ ] Implement tree updating from distribution over nodes
- [ ] Implement tree traversal for recovering parent and sibling node tokens
- [ ] Define node characteristics (argument counts, type, terminal?)
- [ ] Implement fitting constants
- [ ] Implement policy gradient/ figure out how

**Comment by Blair-Johnson** [comment]
sorry lol
